
-- Create article_views table
CREATE TABLE IF NOT EXISTS public.article_views (
  id bigint generated by default as identity primary key,
  article_id bigint references public.articles(id) on delete cascade,
  viewed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  country text default 'Unknown',
  city text default 'Unknown',
  device_type text default 'Unknown',
  ip_hash text -- Optional: to store hashed IP for unique view counting if needed later
);

-- Enable RLS
ALTER TABLE public.article_views ENABLE ROW LEVEL SECURITY;

-- Allow public insert (for tracking views from frontend)
DROP POLICY IF EXISTS "Allow public insert to article_views" ON public.article_views;
CREATE POLICY "Allow public insert to article_views"
  ON public.article_views FOR INSERT
  WITH CHECK (true);

-- Allow authenticated/admin read (for dashboard analytics)
DROP POLICY IF EXISTS "Allow auth read on article_views" ON public.article_views;
CREATE POLICY "Allow auth read on article_views"
  ON public.article_views FOR SELECT
  USING (true); -- Ideally restrict to authenticated users/admins, but for now open for simplicity as per previous pattern

-- Create an index on article_id for faster queries
CREATE INDEX IF NOT EXISTS article_views_article_id_idx ON public.article_views(article_id);
CREATE INDEX IF NOT EXISTS article_views_viewed_at_idx ON public.article_views(viewed_at);
