
-- Create users table
CREATE TABLE IF NOT EXISTS public.users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null,
  is_superadmin boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create user_permissions table
CREATE TABLE IF NOT EXISTS public.user_permissions (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  category_id bigint references public.categories(id) on delete cascade,
  can_add boolean default false,
  can_edit boolean default false,
  can_delete boolean default false,
  unique(user_id, category_id)
);

-- Add ordering columns to categories
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS order_index integer default 0;
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS display_order integer default 0;

-- Enable RLS
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_permissions ENABLE ROW LEVEL SECURITY;

-- Create policies to allow access (since we are not using Supabase Auth)
CREATE POLICY "Allow all access on users" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access on user_permissions" ON public.user_permissions FOR ALL USING (true) WITH CHECK (true);

-- Update existing policies to allow modifications
DROP POLICY IF EXISTS "Allow public read access on categories" ON public.categories;
CREATE POLICY "Allow all access on categories" ON public.categories FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access on articles" ON public.articles;
CREATE POLICY "Allow all access on articles" ON public.articles FOR ALL USING (true) WITH CHECK (true);

-- Insert superadmin
INSERT INTO public.users (username, password, is_superadmin)
VALUES ('superadmin@taapost.net', 'admin123', true)
ON CONFLICT (username) DO NOTHING;
