-- Enable RLS on storage.objects if not already enabled
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

-- 1. Fix Storage RLS Policies (Comprehensive Fix)
-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Media Bucket Public Select" ON storage.objects;
DROP POLICY IF EXISTS "Media Bucket Auth Upload" ON storage.objects;
DROP POLICY IF EXISTS "Media Bucket Auth Update" ON storage.objects;
DROP POLICY IF EXISTS "Media Bucket Auth Delete" ON storage.objects;
DROP POLICY IF EXISTS "Give me access to own folder 1ok22a_0" ON storage.objects;
DROP POLICY IF EXISTS "Give me access to own folder 1ok22a_1" ON storage.objects;
DROP POLICY IF EXISTS "Give me access to own folder 1ok22a_2" ON storage.objects;
DROP POLICY IF EXISTS "Give me access to own folder 1ok22a_3" ON storage.objects;

-- Create a public bucket 'media' if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('media', 'media', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Policy 1: Allow Public Read Access (Anyone can view images)
CREATE POLICY "Media Public Read"
ON storage.objects FOR SELECT
USING ( bucket_id = 'media' );

-- Policy 2: Allow Authenticated Uploads (Logged-in users can upload)
CREATE POLICY "Media Auth Upload"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'media' );

-- Policy 3: Allow Authenticated Updates
CREATE POLICY "Media Auth Update"
ON storage.objects FOR UPDATE
TO authenticated
USING ( bucket_id = 'media' );

-- Policy 4: Allow Authenticated Deletes
CREATE POLICY "Media Auth Delete"
ON storage.objects FOR DELETE
TO authenticated
USING ( bucket_id = 'media' );


-- 2. Add Exclusive Article Support
-- Add is_exclusive column to articles table if it doesn't exist
ALTER TABLE articles 
ADD COLUMN IF NOT EXISTS is_exclusive BOOLEAN DEFAULT FALSE;


-- 3. Site Settings Table (if not exists)
CREATE TABLE IF NOT EXISTS site_settings (
  id BIGINT PRIMARY KEY DEFAULT 1, -- Single row table
  site_name TEXT DEFAULT 'تاء بوست',
  site_description TEXT DEFAULT 'منصة إعلامية رقمية',
  logo_url TEXT,
  primary_color TEXT DEFAULT '#8B4513',
  secondary_color TEXT DEFAULT '#000000',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT single_row CHECK (id = 1)
);

-- Insert default row if not exists
INSERT INTO site_settings (id, site_name, site_description)
VALUES (1, 'تاء بوست', 'منصة إعلامية رقمية')
ON CONFLICT (id) DO NOTHING;

-- Enable RLS for site_settings
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;

-- Allow public read for site settings
CREATE POLICY "Site Settings Public Read"
ON site_settings FOR SELECT
USING (true);

-- Allow authenticated update for site settings
CREATE POLICY "Site Settings Auth Update"
ON site_settings FOR UPDATE
TO authenticated
USING (true);


-- 4. Authors Table (if not exists)
CREATE TABLE IF NOT EXISTS authors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT,
  bio TEXT,
  image TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for authors
ALTER TABLE authors ENABLE ROW LEVEL SECURITY;

-- Allow public read for authors
CREATE POLICY "Authors Public Read"
ON authors FOR SELECT
USING (true);

-- Allow authenticated CRUD for authors
CREATE POLICY "Authors Auth All"
ON authors FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);


-- 5. Link Authors to Articles (if not exists)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'author_id') THEN
        ALTER TABLE articles ADD COLUMN author_id BIGINT REFERENCES authors(id) ON DELETE SET NULL;
    END IF;
END $$;


-- 6. Homepage Sections (if not exists)
CREATE TABLE IF NOT EXISTS homepage_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT,
  type TEXT NOT NULL, -- 'carousel', 'category_grid', 'category_list', 'latest_grid'
  source_type TEXT DEFAULT 'category', -- 'latest', 'category', 'categories'
  category_id BIGINT REFERENCES categories(id),
  source_ids BIGINT[] DEFAULT ARRAY[]::BIGINT[], -- For multiple categories
  count INTEGER DEFAULT 6,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE homepage_sections ENABLE ROW LEVEL SECURITY;

-- Allow public read
CREATE POLICY "Homepage Sections Public Read"
ON homepage_sections FOR SELECT
USING (true);

-- Allow authenticated CRUD
CREATE POLICY "Homepage Sections Auth All"
ON homepage_sections FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);


-- 7. Social Links (if not exists)
CREATE TABLE IF NOT EXISTS social_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform TEXT NOT NULL,
  url TEXT NOT NULL,
  icon TEXT DEFAULT 'Link',
  is_active BOOLEAN DEFAULT TRUE,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE social_links ENABLE ROW LEVEL SECURITY;

-- Allow public read
CREATE POLICY "Social Links Public Read"
ON social_links FOR SELECT
USING (true);

-- Allow authenticated CRUD
CREATE POLICY "Social Links Auth All"
ON social_links FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);
