
-- 1. Create storage bucket for media if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('media', 'media', true)
ON CONFLICT (id) DO NOTHING;

-- 2. Drop existing policies to avoid conflicts (clean slate for media bucket)
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Upload" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Update" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Delete" ON storage.objects;
DROP POLICY IF EXISTS "Allow Upload" ON storage.objects;
DROP POLICY IF EXISTS "Allow Update" ON storage.objects;
DROP POLICY IF EXISTS "Allow Delete" ON storage.objects;

-- 3. Create policies for media bucket
-- Allow public read access to all files in the 'media' bucket
CREATE POLICY "Public Access"
ON storage.objects FOR SELECT
USING ( bucket_id = 'media' );

-- Allow anyone to upload (since we are simulating auth with local storage, we can't use auth.uid())
CREATE POLICY "Allow Upload"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'media' );

-- Allow updates
CREATE POLICY "Allow Update"
ON storage.objects FOR UPDATE
WITH CHECK ( bucket_id = 'media' );

-- Allow deletes
CREATE POLICY "Allow Delete"
ON storage.objects FOR DELETE
USING ( bucket_id = 'media' );

-- 4. Ensure categories table has correct columns for ordering
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS order_index integer DEFAULT 0;
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS display_order integer DEFAULT 0;

-- 5. Ensure RLS is enabled on categories but allows access for our custom auth
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all access on categories" ON public.categories;
CREATE POLICY "Allow all access on categories" ON public.categories FOR ALL USING (true) WITH CHECK (true);

-- 6. Ensure user_permissions table exists and has RLS
CREATE TABLE IF NOT EXISTS public.user_permissions (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  category_id bigint references public.categories(id) on delete cascade,
  can_add boolean default false,
  can_edit boolean default false,
  can_delete boolean default false,
  unique(user_id, category_id)
);

ALTER TABLE public.user_permissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all access on user_permissions" ON public.user_permissions;
CREATE POLICY "Allow all access on user_permissions" ON public.user_permissions FOR ALL USING (true) WITH CHECK (true);

-- 7. Ensure articles table exists (if not already) and has RLS
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all access on articles" ON public.articles;
CREATE POLICY "Allow all access on articles" ON public.articles FOR ALL USING (true) WITH CHECK (true);
